//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyStudent
    {
        public int Fid { get; set; }
        public string FName { get; set; }
        public int FAge { get; set; }
        public string FGender { get; set; }
        public Nullable<int> FMath { get; set; }
        public int FEnglish { get; set; }
        public int FClassId { get; set; }
        public System.DateTime FBirthday { get; set; }
    }
}
